#!/bin/bash

SCRIPT_DIR=$(dirname "$0")
ROOT="$SCRIPT_DIR/.."

INPUT=${1?need input}
NAME=$(basename "$INPUT")
ASM="$ROOT/audio_data.asm"
FLAC="$ROOT/${NAME%.*}.quantized.flac"

shift 1

ffmpeg -i "$INPUT" -f u8 -c:a pcm_u8 -ar 18396 -ac 1 - |
	python "$SCRIPT_DIR/quantize_audio.py" "$ASM" "$@" |
	ffmpeg -f u8 -ar 18396 -ac 1 -i - -y "$FLAC"
